[package]
name = "netwatch"
version = "1.0.0"
authors = ["Gatis Peisenieks <peisenieks@gmail.com>"]
license = "MIT"

[dependencies]
libc = { version = "0.2", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
