[build]
target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
#rustflags = ["-Ctarget-feature=-crt-static", "-Clink-self-contained=on", "-L/usr/lib/x86_64-linux-musl", "-Clink-args=--dynamic-linker /lib/ld-musl-x86_64.so.1"]
rustflags = ["-lc"]
